services:
  - type: web
    name: todo-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r ../requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd backend && gunicorn todo_project.wsgi:application --bind 0.0.0.0:$PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: todo_project.settings

databases:
  - name: todo-db
    databaseName: todo_db
    user: todo_user
    plan: free


